services:

  leaderboardDBMY:
    image: postgres:latest
    container_name: leaderboardDBMY
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=LeaderboardDB
    ports:
      - 5432:5432



  leaderboardDB:
    image: postgres:latest
    container_name: leaderboardDB
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=LeaderboardDB
  leaderboardAPI:
    image: rebuyboy/leaderboardapi:latest
    restart: always
    ports:
      - 8082:8081
    depends_on:
      - leaderboardDB
    links:
      - leaderboardDB
